#ifndef USER_H
#define USER_H

#include <string>

enum class Role {
    User,
    Admin
};

struct UserInfo {
    std::string username;    // username cố định
    std::string fullName;
    std::string email;
    Role role;
    bool isActive;
    bool isAutoGeneratedPassword;
};

#endif // USER_H
